### ISSUE TITLE
failed to create the waypoint_global_planner

### ISSUE THREAD

**Issue by aarontan94** [gkouros/waypoint-global-planner#1]
hello,

could you provide some instructions on how to implement your planner as the global planner?

I am using the [husky navigation stack](http://wiki.ros.org/husky_navigation)

I added the following to the move_base launch file 

 `<param name="base_global_planner" value="waypoint_global_planner/WaypointGlobalPlanne" />` 

`<rosparam file="$(find waypoint_global_planner)/config/base_global_planner_params.yaml" command="load"/>`

When I launch the launch file however, i get the following error:

`[FATAL] [1528930206.441060089, 162.174000000]: Failed to create the waypoint_global_planner/WaypointGlobalPlanne planner, are you sure it is properly registered and that the containing library is built? Exception: According to the loaded plugin descriptions the class waypoint_global_planner/WaypointGlobalPlanne with base class type nav_core::BaseGlobalPlanner does not exist. Declared types are  carrot_planner/CarrotPlanner global_planner/GlobalPlanner navfn/NavfnROS waypoint_global_planner/WaypointGlobalPlanner`

I believe I am not implementing your global planner right, any instruction would be appreciated. 

Thank you

**Comment by gkouros** [comment]
Hi,

There is an "r" missing in the param value:
<param name="base_global_planner" value="waypoint_global_planner/WaypointGlobalPlanne" />
should be
<param name="base_global_planner" value="waypoint_global_planner/WaypointGlobalPlanner" />

However, you don't need to use this line since the parameter "base_global_planner" is set from the configuration file you load using rosparam, provided that you load the configuration file inside the
namespace of move_base.

Hope that helps.

**Comment by aarontan94** [comment]
@gkouros thank you for your prompt response, your suggestion worked.
