### ISSUE TITLE
Cannot modify the orientation angle of the target point？

### ISSUE THREAD

**Issue by ju-mingyue** [gkouros/waypoint-global-planner#6]
When I use this program, I can follow the route point I determined to run, but the flaw is that there are the following problems:
1. How to modify the direction angle of the last target point?
2. How to save the marked points so that they can be used directly next time instead of re-calibration every time.
3. For example, if I control the robot to a certain point, how do I record the point and publish it to the global planner?

**Comment by ju-mingyue** [comment]
@gkouros

**Comment by gkouros** [comment]
Hi,
Sorry for the late reply.
1) I mention in the instructions that the final orientation equals the angle between the two last waypoints.
2) You can record the published global plan in a rosbag and then use the rosbag as input to the planner via the external\_path topic. Otherwise you can extend the planner to save a path in a yaml file and then load it in next launches.
3) I don't understand this question. Can you elaborate?
